networks:
  fb-network:
    driver: bridge
services:
  filebrowser:
    environment:
    - FB_BASEURL=/filebrowser
    - FB_10002=80
    - FB_ADDRESS=0.0.0.0
    image: filebrowser/filebrowser:latest
    networks:
    - fb-network
    ports:
    - 10000:80
    volumes:
    - fb_data:/srv
    - fb_config:/config
version: '3.8'
volumes:
  fb_config: null
  fb_data: null
