version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    ports:
      - 9999:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: JKlJq
      WORDPRESS_DB_PASSWORD: 5auTGhCuQlccOugGlioh
      WORDPRESS_DB_NAME: BGwgxKKkfF
    volumes:
      - wp_data:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: BGwgxKKkfF
      MYSQL_USER: JKlJq
      MYSQL_PASSWORD: 5auTGhCuQlccOugGlioh
      MYSQL_ROOT_PASSWORD: b5XzVSHnAW5u0mEHsso3kFkqaQNM4gJDm7Wfv61A
    volumes:
      - db_data:/var/lib/mysql

volumes:
  wp_data:
  db_data:
