version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    ports:
      - 10000:80   # Expose WordPress on host port 8080
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: UWzIn
      WORDPRESS_DB_PASSWORD: a2pwEDix9CU7SfS7keM3
      WORDPRESS_DB_NAME: MzVcpSnygn
    networks:
      - wp-network
    volumes:
      - wp_data:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: MzVcpSnygn
      MYSQL_USER: UWzIn
      MYSQL_PASSWORD: a2pwEDix9CU7SfS7keM3
      MYSQL_ROOT_PASSWORD: aLrwzvrWOIiZru5aUzTbLhEQy0xaGLVFWDWXCyvG
    expose:
      - 3306  # Expose only to other containers in the same network
    networks:
      - wp-network
    volumes:
      - db_data:/var/lib/mysql

volumes:
  wp_data:
  db_data:

networks:
  wp-network:
    driver: bridge
